version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.15'
      - run: node --version
workflows:
  fitbit-steps-to-pixela:
    jobs:
      - install-node
      - node/run:
          yarn-run: main
