version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  fitbit-steps-to-pixela:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.15'
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run
          command: yarn main
workflows:
  fitbit_steps_to_pixela:
    jobs:
      - fitbit-steps-to-pixela
